import type { Metadata } from 'next'
import styles from './page.module.css'
import './globals.css'
import Navbar from '../../components/navbar'
import Head from 'next/head'


export const metadata: Metadata = {
  title: 'Stray Pets Adoption',
  description: 'Generated by create next app',
  authors:{name:'Clark Leovison C. Rey, Jerome Evangelista, Junella Magalong, Krizia Santos, Phillip Parot, Arielle Castillo'}
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
      <body className={styles.body}>{children}
       <header><Navbar/></header>
      </body>
    </html>
  )
}
