import Image from 'next/image'
import styles from './page.module.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home | Stray Pets Adoption',
  description: 'Generated by create next app',
  authors:{name:'Clark Leovison C. Rey, Jerome Evangelista, Junella Magalong, Krizia Santos, Phillip Parot, Arielle Castillo'}
}

export default function Home() {
  return (
    <main>

    </main>
  )
}
